spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/JobPortal
    username: postgres
    password: niharika

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  web:
    error:
      include-message: always
      include-binding-errors: always
